title: Elense Studio
email: contact@elense.com
description: >- # this means to ignore newlines until "baseurl:"
  Portfolio of Elense Software, Engineering, and Leathercraft.
baseurl: ""
url: "https://elensestudio.com" # Twoja w≈Çasna domena

# Collections for portfolio
collections:
  software:
    output: true
    permalink: /software/:path/
  engineering:
    output: true
    permalink: /engineering/:path/
  leathercraft:
    output: true
    permalink: /leathercraft/:path/

# Build settings
# remote_theme: thedevslot/WhatATheme
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
