title: Elense Studio
email: contact@elense.com
description: >- # this means to ignore newlines until "baseurl:"
  Portfolio of Elense Software, Engineering, and Leathercraft.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Collections for portfolio
collections:
  software:
    output: true
    permalink: /software/:path/
  engineering:
    output: true
    permalink: /engineering/:path/
  leathercraft:
    output: true
    permalink: /leathercraft/:path/

# Build settings
theme: minima
plugins:
  - jekyll-feed
